name = "based_pg"
version = "1.0.0"
description = "A postgres adapter for based"
gleam = "~> 1.0"

licences = ["Apache-2.0"]
repository = { type = "github", user = "stndrs", repo = "based_pg" }

[dependencies]
gleam_stdlib = "~> 0.38 or ~> 1.0"
gleam_pgo = "~> 0.10"
based = ">= 1.0.0 and < 2.0.0"

[dev-dependencies]
gleeunit = "~> 1.0"
